name: xxx-dev
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - cmake=3.24
  - clang-format=16.0
  - clang-tools=16.0
  - clangdev=16.0 # We need this since clang-tools don't install clang headers for some reason.
  - doxygen
  - pip
  - pip:
    - -r requirements-dev.txt
